@startuml

start

split
:BuildingConstructionCancelRequested;
split again
:BuildingDeconstructionCancelRequested;
end split

if (Construction site exist?) then (true)
    :ResourcesLeaseReleaseRequested;
    if (Resource lease exist?) then (true)
    else (false)
        #red:TODO: resource lease does not exist - canceled before?;
        detach;
    endif
else (false)
    #red:TODO: construction site does not exist - canceled before?;
    detach;
endif

split
    :ResourcesLeaseReleased;
    detach
split again
    :ResourceEarned;
    if (Storage full?) then (true)
        :StorageFilled;
        detach
    else (false)
    end
    endif
end split

@enduml