@startuml

start

:BuildingConstructionCancelRequested;

if (Construction site exist?) then (true)
    if (Resource lease exist?) then (true)
        :ResourcesLeaseReleaseRequested;
    else (false)
        #red:TODO: resource lease does not exist - canceled before?;
    endif
else (false)
    #red:TODO: construction site does not exist - canceled before?;
endif

:ResourcesLeaseReleased;
:ResourceEarned;

if (Storage full?) then (true)
    :StorageFilled;
else (false)
endif
detach

end

@enduml