@startuml

start

:BuildingDestructionRequested;
if (Building lvl > 0?) then (true)
    :ScheduledEventRequested;
    -[dotted]-> Deffered execution;
    :BuildingDestructionFinished;
    :ResourcesRefundRequested;
    :ResourcesRefunded;
    :ResourcesEarned;
    if (Storage full?) then (true)
        :StorageFilled;
    endif
    end
else (false)
    #red:TODO1: level to low;
    end
endif

@enduml