@startuml

start

:BuildingConstructionRequested;

if (Enough resources available?) then (true)
    :BuildingConstructionResourcesLeaseRequested;
    if (Enough resources available?) then (true)
        :BuildingConstructionResourcesLeased;
        split
            :ResourcesSpent;
            if(Storage was full and now is not?) then (true)
                :StorageSpaceAvailable;
                detach
            else
                end
            endif
        split again
            :ScheduledEventRequested;
            -[dotted]-> Deffered execution;
            :BuildingConstructionFinished;
            split
                if (Resource lease still exist?) then (true)
                    :ResourceLeaseUsed;
                else (false)
                    #red:TODO: resource lease already destroyed
                    construction canceled?
                    event fired multiple times?;
                endif
            split again
                if (Construction site still exist?) then (true)
                    :BuildingLeveledUp;
                else (false)
                    #red:TODO: construction site already gone
                    construction canceled?
                    event fired multiple times?;
                endif
            end split
        end
        end split
    else (false)
        #red:TODO: no resources;
        end
    endif
else (false)
    #red:TODO: no resources;
    end
endif




@enduml